-- 1. Create the contacts table
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    organisation TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to insert contact form submissions (no reading/updates allowed)
CREATE POLICY "Allow public insert to contacts" ON contacts 
    FOR INSERT 
    WITH CHECK (true);

-- 2. Create the inquiries table for bulk queries
CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    org_name TEXT NOT NULL,
    org_type TEXT NOT NULL,
    quantity TEXT NOT NULL,
    printer_model TEXT NOT NULL,
    timeline TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    message TEXT
);

-- Enable RLS for inquiries table
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to insert inquiry submissions (no reading/updates allowed)
CREATE POLICY "Allow public insert to inquiries" ON inquiries 
    FOR INSERT 
    WITH CHECK (true);
